'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ged:8080/alfresco/api/-default-/public/cmis/versions/1.1/atom")>  _
        Public Property cmis_connection() As String
            Get
                Return CType(Me("cmis_connection"),String)
            End Get
            Set
                Me("cmis_connection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ged")>  _
        Public Property cmis_user() As String
            Get
                Return CType(Me("cmis_user"),String)
            End Get
            Set
                Me("cmis_user") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("heinen")>  _
        Public Property cmis_pwd() As String
            Get
                Return CType(Me("cmis_pwd"),String)
            End Get
            Set
                Me("cmis_pwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\scan_in")>  _
        Public Property pdf_in() As String
            Get
                Return CType(Me("pdf_in"),String)
            End Get
            Set
                Me("pdf_in") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\pdf_error")>  _
        Public Property pdf_error() As String
            Get
                Return CType(Me("pdf_error"),String)
            End Get
            Set
                Me("pdf_error") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\scan_log.txt")>  _
        Public Property log_file() As String
            Get
                Return CType(Me("log_file"),String)
            End Get
            Set
                Me("log_file") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\test.bmp")>  _
        Public Property img_temp() As String
            Get
                Return CType(Me("img_temp"),String)
            End Get
            Set
                Me("img_temp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\pdf_ok")>  _
        Public Property pdf_ok() As String
            Get
                Return CType(Me("pdf_ok"),String)
            End Get
            Set
                Me("pdf_ok") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\srv08\Share\@Fichiers_XML\Liste_categorie_QR_general.xml")>  _
        Public Property xml_file() As String
            Get
                Return CType(Me("xml_file"),String)
            End Get
            Set
                Me("xml_file") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mbr@heinen.eu")>  _
        Public Property em_martha() As String
            Get
                Return CType(Me("em_martha"),String)
            End Get
            Set
                Me("em_martha") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sec@heinen.eu")>  _
        Public Property em_cuisine() As String
            Get
                Return CType(Me("em_cuisine"),String)
            End Get
            Set
                Me("em_cuisine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mrx@heinen.eu;fbs@heinen.eu")>  _
        Public Property em_bet() As String
            Get
                Return CType(Me("em_bet"),String)
            End Get
            Set
                Me("em_bet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sec@heinen.eu")>  _
        Public Property em_sec() As String
            Get
                Return CType(Me("em_sec"),String)
            End Get
            Set
                Me("em_sec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mrx@heinen.eu")>  _
        Public Property em_f111() As String
            Get
                Return CType(Me("em_f111"),String)
            End Get
            Set
                Me("em_f111") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("fbs@heinen.eu")>  _
        Public Property em_inconnu() As String
            Get
                Return CType(Me("em_inconnu"),String)
            End Get
            Set
                Me("em_inconnu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\QRCODE\pdf_tmp")>  _
        Public Property pdf_temp() As String
            Get
                Return CType(Me("pdf_temp"),String)
            End Get
            Set
                Me("pdf_temp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mrx@heinen.eu;fbs@heinen.eu")>  _
        Public Property em_erreur() As String
            Get
                Return CType(Me("em_erreur"),String)
            End Get
            Set
                Me("em_erreur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ged:8080/alfresco/api/-default-/public/cmis/versions/1.0/atom")>  _
        Public Property cmis_conn_10() As String
            Get
                Return CType(Me("cmis_conn_10"),String)
            End Get
            Set
                Me("cmis_conn_10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T:\SCAN\QR_Code\Eplan")>  _
        Public Property pdf_in_2() As String
            Get
                Return CType(Me("pdf_in_2"),String)
            End Get
            Set
                Me("pdf_in_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property tb_pdf_ok() As String
            Get
                Return CType(Me("tb_pdf_ok"),String)
            End Get
            Set
                Me("tb_pdf_ok") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property tb_pdf_ko() As String
            Get
                Return CType(Me("tb_pdf_ko"),String)
            End Get
            Set
                Me("tb_pdf_ko") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.QR_decode.My.MySettings
            Get
                Return Global.QR_decode.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
